### ISSUE TITLE
Clubs forms QA: Select dropdowns shouldn't make me feel like I can type something.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2251] opened 2016-09-27 18:46 UTC
When I select an option from "How did you hear", it looks like this...

![image](https://cloud.githubusercontent.com/assets/25212/18887201/0bc38a82-84a8-11e6-8595-ff7b916f828f.png)

This makes it feel like I can type something here, or should - since it's focused and blinking. But really, I can't. Can we disable editing of these choices and unfocus the field after a selection?

**Comment by Pomax** [comment] 2016-09-27 19:22
duplicate of https://github.com/mozilla/learning.mozilla.org/issues/2247, they both use the `react-select` component. We'd have to replace it, or file the issue against their component.

**Closed by Pomax** 2016-09-27 19:22 UTC
Labels: QA
