### ISSUE TITLE
Add tests/test framework that can catch not-locale-based strings - server

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#1957] opened 2016-07-11 19:28 UTC
We might not need this, but as much tests coverage possible is better than none.

**Comment by alanmoo** [comment] 2016-07-11 20:11
@Pomax was this suggested by you? Can you give a specific example of this?

**Comment by hannahkane** [comment] 2016-08-08 16:58
Dupe of #2038

**Closed by hannahkane** 2016-08-08 16:58 UTC
Labels: Going Global
