### ISSUE TITLE
Gigabit QA: Missing icons in tabs when view is narrow.

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2315] opened 2016-10-07 19:37 UTC
![image](https://cloud.githubusercontent.com/assets/25212/19203188/b91ba4a0-8c8a-11e6-8c1e-b8a3180bf623.png)

#2228

**Comment by gvn** [comment] 2016-10-07 20:15
Dupe of #2297

**Closed by gvn** 2016-10-07 20:15 UTC
Labels: QA
