### ISSUE TITLE
From CC app success page can't get back to main Clubs page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2056] opened 2016-08-03 21:53 UTC
From the CC application success page, clicking on "Mozilla Clubs" in the navigation does nothing, since the user is technically still on that page. Can we prompt the user to refresh the page with a "Back to Clubs main page" link or something like that?

**Comment by Pomax** [comment] 2016-08-09 21:43
duplicate of https://github.com/mozilla/learning.mozilla.org/issues/2054, which has a PR open now to address the issue, too.

**Closed by Pomax** 2016-08-09 21:43 UTC
Labels: Local Impact
