### ISSUE TITLE
tab rendering difference on club pages between mofostaging and prod

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2186] opened 2016-09-08 15:43 UTC
It looks like mofostaging based on master no longer shows the tabs on the clubs page correctly, compared to production.

staging:

![screenshot 45](https://cloud.githubusercontent.com/assets/177243/18356108/4706d9f8-75a0-11e6-9051-6c7f96645d33.png)

production:

![screenshot 46](https://cloud.githubusercontent.com/assets/177243/18356112/49be1ee0-75a0-11e6-8797-5f4759796bf9.png)

**Comment by gvn** [comment] 2016-09-08 17:14
Dupe of #2185

**Closed by gvn** 2016-09-08 17:15 UTC
Labels: bug, Local Impact
